(in-package #:common-rate.domain)

(defun normalize-crypto (sym)
  (or (cdr (assoc (string-upcase sym)
                  '(("BTC" . "bitcoin")
                    ("ETH" . "ethereum")
                    ("SOL" . "solana")
                    ("BNB" . "binancecoin")
                    ("XRP" . "ripple")
                    ("ADA" . "cardano")
                    ("DOGE" . "dogecoin")
                    ("DOT" . "polkadot")
                    ("LTC" . "litecoin")
                    ("LINK" . "chainlink")
                    ("XLM" . "stellar")
                    ("AVAX" . "avalanche-2")
                    ("TRX" . "tron")
                    ("UNI" . "uniswap")
                    ("NEAR" . "near")
                    ("ATOM" . "cosmos")
                    ("ALGO" . "algorand")
                    ("VET" . "vechain")
                    ("FIL" . "filecoin")
                    ("XMR" . "monero")
                    ("APT" . "aptos")
                    ("ARB" . "arbitrum")
                    ("OP" . "optimism")
                    ("MATIC" . "polygon"))
                  :test #'string=))
      (string-downcase sym)))
